// <auto-generated />
using System;
using System.Text.Json;
using DJBrate.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DJBrate.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318135219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DJBrate.API.Models.AiConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ai_conversation_messages");
                });

            modelBuilder.Entity("DJBrate.API.Models.AiModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.HasKey("Id");

                    b.ToTable("ai_model_configs");
                });

            modelBuilder.Entity("DJBrate.API.Models.AiMoodMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text")
                        .HasColumnName("ai_reasoning");

                    b.PrimitiveCollection<string[]>("DetectedGenres")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_genres");

                    b.Property<string>("DetectedMood")
                        .HasColumnType("text")
                        .HasColumnName("detected_mood");

                    b.Property<string>("FlowUsed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_used");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float?>("TargetAcousticness")
                        .HasColumnType("real")
                        .HasColumnName("target_acousticness");

                    b.Property<float?>("TargetDanceability")
                        .HasColumnType("real")
                        .HasColumnName("target_danceability");

                    b.Property<float?>("TargetEnergy")
                        .HasColumnType("real")
                        .HasColumnName("target_energy");

                    b.Property<float?>("TargetTempo")
                        .HasColumnType("real")
                        .HasColumnName("target_tempo");

                    b.Property<float?>("TargetValence")
                        .HasColumnType("real")
                        .HasColumnName("target_valence");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("ai_mood_mappings");
                });

            modelBuilder.Entity("DJBrate.API.Models.ListeningStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("AvgEnergy")
                        .HasColumnType("real")
                        .HasColumnName("avg_energy");

                    b.Property<float?>("AvgTempo")
                        .HasColumnType("real")
                        .HasColumnName("avg_tempo");

                    b.Property<float?>("AvgValence")
                        .HasColumnType("real")
                        .HasColumnName("avg_valence");

                    b.Property<string>("DominantMood")
                        .HasColumnType("text")
                        .HasColumnName("dominant_mood");

                    b.Property<int>("PlaylistsGenerated")
                        .HasColumnType("integer")
                        .HasColumnName("playlists_generated");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<string>("TopGenre")
                        .HasColumnType("text")
                        .HasColumnName("top_genre");

                    b.Property<int>("TracksLiked")
                        .HasColumnType("integer")
                        .HasColumnName("tracks_liked");

                    b.Property<int>("TracksSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("tracks_skipped");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StatDate")
                        .IsUnique();

                    b.ToTable("listening_stats");
                });

            modelBuilder.Entity("DJBrate.API.Models.McpToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<JsonDocument>("InputParameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_parameters");

                    b.Property<JsonDocument>("OutputResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_result");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("mcp_tool_calls");
                });

            modelBuilder.Entity("DJBrate.API.Models.MoodSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AiConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_config_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<float?>("Danceability")
                        .HasColumnType("real")
                        .HasColumnName("danceability");

                    b.Property<float?>("EnergyLevel")
                        .HasColumnType("real")
                        .HasColumnName("energy_level");

                    b.Property<string>("PromptText")
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.PrimitiveCollection<string[]>("SelectedGenres")
                        .HasColumnType("text[]")
                        .HasColumnName("selected_genres");

                    b.Property<string>("SelectedMood")
                        .HasColumnType("text")
                        .HasColumnName("selected_mood");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiConfigId");

                    b.HasIndex("UserId");

                    b.ToTable("mood_sessions");
                });

            modelBuilder.Entity("DJBrate.API.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SpotifyPlaylistId")
                        .HasColumnType("text")
                        .HasColumnName("spotify_playlist_id");

                    b.Property<int>("TrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("track_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("playlists");
                });

            modelBuilder.Entity("DJBrate.API.Models.PlaylistTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("Acousticness")
                        .HasColumnType("real")
                        .HasColumnName("acousticness");

                    b.Property<string>("AlbumName")
                        .HasColumnType("text")
                        .HasColumnName("album_name");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist_name");

                    b.Property<float?>("Danceability")
                        .HasColumnType("real")
                        .HasColumnName("danceability");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<float?>("Energy")
                        .HasColumnType("real")
                        .HasColumnName("energy");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<string>("SpotifyArtistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_artist_id");

                    b.Property<string>("SpotifyTrackId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_track_id");

                    b.Property<float?>("Tempo")
                        .HasColumnType("real")
                        .HasColumnName("tempo");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_name");

                    b.Property<float?>("Valence")
                        .HasColumnType("real")
                        .HasColumnName("valence");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("playlist_tracks");
                });

            modelBuilder.Entity("DJBrate.API.Models.TrackFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feedback_type");

                    b.Property<Guid>("PlaylistTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_track_id");

                    b.Property<string>("SpotifyTrackId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_track_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistTrackId");

                    b.HasIndex("UserId", "PlaylistTrackId")
                        .IsUnique();

                    b.ToTable("track_feedbacks");
                });

            modelBuilder.Entity("DJBrate.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("SpotifyAccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_access_token");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_id");

                    b.Property<string>("SpotifyRefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_refresh_token");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("DJBrate.API.Models.UserTopArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist_name");

                    b.PrimitiveCollection<string[]>("Genres")
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<int>("RankPosition")
                        .HasColumnType("integer")
                        .HasColumnName("rank_position");

                    b.Property<string>("SpotifyArtistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_artist_id");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("TimeRange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_range");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SpotifyArtistId", "TimeRange")
                        .IsUnique();

                    b.ToTable("user_top_artists");
                });

            modelBuilder.Entity("DJBrate.API.Models.UserTopTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist_name");

                    b.Property<int>("RankPosition")
                        .HasColumnType("integer")
                        .HasColumnName("rank_position");

                    b.Property<string>("SpotifyArtistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_artist_id");

                    b.Property<string>("SpotifyTrackId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spotify_track_id");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("TimeRange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_range");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SpotifyTrackId", "TimeRange")
                        .IsUnique();

                    b.ToTable("user_top_tracks");
                });

            modelBuilder.Entity("DJBrate.API.Models.AiConversationMessage", b =>
                {
                    b.HasOne("DJBrate.API.Models.MoodSession", "MoodSession")
                        .WithMany("AiConversationMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodSession");
                });

            modelBuilder.Entity("DJBrate.API.Models.AiMoodMapping", b =>
                {
                    b.HasOne("DJBrate.API.Models.MoodSession", "MoodSession")
                        .WithOne("AiMoodMapping")
                        .HasForeignKey("DJBrate.API.Models.AiMoodMapping", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodSession");
                });

            modelBuilder.Entity("DJBrate.API.Models.ListeningStat", b =>
                {
                    b.HasOne("DJBrate.API.Models.User", "User")
                        .WithMany("ListeningStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DJBrate.API.Models.McpToolCall", b =>
                {
                    b.HasOne("DJBrate.API.Models.MoodSession", "MoodSession")
                        .WithMany("McpToolCalls")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodSession");
                });

            modelBuilder.Entity("DJBrate.API.Models.MoodSession", b =>
                {
                    b.HasOne("DJBrate.API.Models.AiModelConfig", "AiConfig")
                        .WithMany("MoodSessions")
                        .HasForeignKey("AiConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DJBrate.API.Models.User", "User")
                        .WithMany("MoodSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DJBrate.API.Models.Playlist", b =>
                {
                    b.HasOne("DJBrate.API.Models.MoodSession", "MoodSession")
                        .WithOne("Playlist")
                        .HasForeignKey("DJBrate.API.Models.Playlist", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DJBrate.API.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DJBrate.API.Models.PlaylistTrack", b =>
                {
                    b.HasOne("DJBrate.API.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("DJBrate.API.Models.TrackFeedback", b =>
                {
                    b.HasOne("DJBrate.API.Models.PlaylistTrack", "PlaylistTrack")
                        .WithMany("TrackFeedbacks")
                        .HasForeignKey("PlaylistTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DJBrate.API.Models.User", "User")
                        .WithMany("TrackFeedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistTrack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DJBrate.API.Models.UserTopArtist", b =>
                {
                    b.HasOne("DJBrate.API.Models.User", "User")
                        .WithMany("UserTopArtists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DJBrate.API.Models.UserTopTrack", b =>
                {
                    b.HasOne("DJBrate.API.Models.User", "User")
                        .WithMany("UserTopTracks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DJBrate.API.Models.AiModelConfig", b =>
                {
                    b.Navigation("MoodSessions");
                });

            modelBuilder.Entity("DJBrate.API.Models.MoodSession", b =>
                {
                    b.Navigation("AiConversationMessages");

                    b.Navigation("AiMoodMapping");

                    b.Navigation("McpToolCalls");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("DJBrate.API.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("DJBrate.API.Models.PlaylistTrack", b =>
                {
                    b.Navigation("TrackFeedbacks");
                });

            modelBuilder.Entity("DJBrate.API.Models.User", b =>
                {
                    b.Navigation("ListeningStats");

                    b.Navigation("MoodSessions");

                    b.Navigation("Playlists");

                    b.Navigation("TrackFeedbacks");

                    b.Navigation("UserTopArtists");

                    b.Navigation("UserTopTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
